### ISSUE TITLE
Cookies are not synched with WKWebView

### ISSUE THREAD

**Issue by mkihellas** [CWBudde/cordova-plugin-wkwebview-inject-cookie#3]
Hello,
i'm trying to make cookies work on my iOS cordova app using your cookie injection plugin combined with Oracle's WKWebView plugin (https://github.com/oracle/cordova-plugin-wkwebview-file-xhr). I've called the cookie plugin setup as it's on the documentation:

`document.addEventListener('deviceready', () => {
  wkWebView.injectCookie('mydomain.com/mypath');
});`

And then using CookieMaster plugin (https://github.com/RTK/cordova-cookie-emperor), i'm trying to set the cookies but they're not set at all.

Can you please describe if the plugin has to be combined with some specific WKWebView cordova plugin other than Oracle's (i've already tried all available WKWebView plugins) or if it's something wrong with the plugin call? Thank you in advance.

**Comment by CWBudde** [comment]
The plugin has been tested mainly with the ionic plugin for wkwebview (see https://github.com/ionic-team/cordova-plugin-ionic-webview). But it is independent and does not require this plugin. Any wkWebView plugin should work.

Also the plugin was not meant to write cookies directly so that these can be used already. It just triggers the sync mechanism so that cookies will be synced between the WkWebView storage and the browser storage (oversimplified explanation). Without, the sync process will only start after the application has been minimized (paused) and resumed again.

So first you should test if your app and the cookies work after this "treatment" (minimization + maximization). Once it does, you can fix the missing gap from the very first install to the first time of mini/max with this plugin.

If you want to use this plugin to actually store and master cookies a few more lines of code in the plugin are necessary. I had them in during development, but reduced the code to the bare minimum, just to make it start the syncing process after the very first install of the app.
